# Build and test a Java project with Maven, and compute and report test coverage 

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: building, testing and quality analysis
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    env:
      DISPLAY: ":99.0"

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
      
    - name: Set up with Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Set up Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &
        
    - name: Build with Maven (including running all tests)
      run: mvn -B package --file pom.xml
      
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
        generate-branches-badge: true
        generate-summary: true
        
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Check git status before commit
      run: |
        git status 
        git log -1
    
    - name: Add, commit, and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add *.svg *.json
        git commit -m "commit coverage badge and summary" || echo "No changes to commit"
        git push origin HEAD:${{ github.head_ref }} --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/
        
    - name: Comment on PR with coverage percentages
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        REPORT=$(<.github/badges/coverage-summary.json)
        COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
        BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
        NEWLINE=$'\n'
        BODY="## Test Coverage Summary ${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
        gh pr comment ${{github.event.pull_request.number}} -b "${BODY}"
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
